import { useState, useRef } from "react";
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area, Legend,
} from "recharts";
import { Download, TrendingUp, TrendingDown, Package, AlertTriangle, CheckCircle, Clock, Printer, FileText, File } from "lucide-react";
import { toast } from "sonner";
import { useInventory } from "../context/InventoryContext";
import { useAssignments } from "../context/AssignmentsContext";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../components/ui/dialog";

const COLORS = ["#B0BF00", "#1a1d27", "#94a3b8", "#64748b", "#C5D300", "#8BA000"];

const CARD = "bg-white/80 backdrop-blur-xl rounded-xl shadow-[0_4px_20px_rgba(176,191,0,0.08)] border border-[#B0BF00]/20 p-5 hover:shadow-[0_8px_30px_rgba(176,191,0,0.15)] transition-all duration-300";

export default function Reports() {
  const [period, setPeriod] = useState("6months");
  const [showPrintPreview, setShowPrintPreview] = useState(false);
  const [showFormatDialog, setShowFormatDialog] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const { inventory, loading: inventoryLoading } = useInventory();
  const { assignments, loading: assignmentsLoading } = useAssignments();

  const handleExport = (type: string) => {
    toast.success(`${type} report exported successfully.`);
  };

  const handleGenerateReport = (format: "pdf" | "csv") => {
    setShowFormatDialog(false);
    
    if (format === "pdf") {
      // Generate PDF via print
      setShowPrintPreview(true);
      setTimeout(() => {
        window.print();
      }, 100);
      toast.success("PDF report ready for download. Please use your browser's print dialog.");
    } else {
      // Generate CSV
      handleExportCSV();
    }
  };

  const handleExportCSV = () => {
    // Create CSV content with professional table format
    const csvRows = [];
    
    // === HEADER SECTION ===
    csvRows.push("DIGITAL MINDS BPO SERVICES INC.");
    csvRows.push("INVENTORY MANAGEMENT SYSTEM - COMPREHENSIVE REPORT");
    csvRows.push(`Report Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}`);
    csvRows.push(`Generated by: Jeremy Sendon (Admin)`);
    csvRows.push(""); // Separator
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(""); // Separator
    
    // === EXECUTIVE SUMMARY ===
    csvRows.push("EXECUTIVE SUMMARY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    
    // Summary table with proper alignment
    csvRows.push("Metric,Value,Details");
    csvRows.push(`Total Assets,${totalAssets},Across all categories`);
    csvRows.push(`Assets In Stock,${totalInStock},"${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of total inventory"`);
    csvRows.push(`Low Stock Items,${totalLowStock},Requires restocking`);
    csvRows.push(`Out of Stock Items,${totalOutOfStock},Urgent action needed`);
    csvRows.push(`Under Maintenance,${totalUnderMaintenance},Currently being serviced`);
    csvRows.push(`Total Inventory Value,"₱${totalInventoryValue.toLocaleString()}",Current market value`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === STOCK DISTRIBUTION BY CATEGORY ===
    csvRows.push("STOCK DISTRIBUTION BY CATEGORY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Category,In Stock,Low Stock,Out of Stock,Total Quantity,Percentage");
    
    const totalItems = stockByType.reduce((sum, item) => sum + item.total, 0);
    stockByType.forEach(item => {
      const percentage = totalItems > 0 ? Math.round((item.total / totalItems) * 100) : 0;
      csvRows.push(`"${item.name}",${item.inStock},${item.lowStock},${item.outOfStock},${item.total},${percentage}%`);
    });
    
    // Add totals row
    csvRows.push(`"TOTAL",${stockByType.reduce((sum, item) => sum + item.inStock, 0)},${stockByType.reduce((sum, item) => sum + item.lowStock, 0)},${stockByType.reduce((sum, item) => sum + item.outOfStock, 0)},${totalItems},100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === DETAILED INVENTORY LISTING ===
    csvRows.push("DETAILED INVENTORY LISTING");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Asset Name,SKU,Category,Brand,Model,Serial Number,Location,Qty,Unit Price,Total Value,Status,Condition,Purchase Date");
    
    // Sort inventory by category then by asset name
    const sortedInventory = [...inventory].sort((a, b) => {
      if (a.category !== b.category) return a.category.localeCompare(b.category);
      return a.assetName.localeCompare(b.assetName);
    });
    
    sortedInventory.forEach(item => {
      csvRows.push(
        `\"${item.assetName}\",\"${item.sku}\",\"${item.category}\",\"${item.brand}\",\"${item.model}\",\"${item.serialNumber}\",\"${item.location}\",${item.quantity},\"₱${item.price.toLocaleString()}\",\"₱${(item.price * item.quantity).toLocaleString()}\",\"${item.stockStatus}\",\"${item.condition || 'N/A'}\",\"${item.purchaseDate || 'N/A'}\"`
      );
    });
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === TOP ASSETS BY VALUE ===
    csvRows.push("TOP ASSETS BY VALUE");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Rank,Asset Name,SKU,Category,Quantity,Unit Price,Total Value,Status,Condition");
    
    topAssets.slice(0, 10).forEach((item, index) => {
      csvRows.push(
        `${index + 1},"${item.name}","${item.sku}","${item.category}",${item.qty},"₱${item.price.toLocaleString()}","₱${item.totalValue.toLocaleString()}","${item.stockStatus}","${item.condition}"`
      );
    });
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === INVENTORY VALUE BREAKDOWN ===
    csvRows.push("INVENTORY VALUE BREAKDOWN BY CATEGORY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Category,Total Value,Percentage of Total");
    
    const totalValue = inventoryValueByCategory.reduce((sum, cat) => sum + cat.value, 0);
    inventoryValueByCategory.forEach(cat => {
      const percentage = totalValue > 0 ? Math.round((cat.value / totalValue) * 100) : 0;
      csvRows.push(`"${cat.name}","₱${cat.value.toLocaleString()}",${percentage}%`);
    });
    csvRows.push(`"TOTAL","₱${totalValue.toLocaleString()}",100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === ASSET CONDITION SUMMARY ===
    csvRows.push("ASSET CONDITION SUMMARY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Condition,Quantity,Percentage");
    
    const totalConditionItems = conditionData.reduce((sum, d) => sum + d.value, 0);
    conditionData.forEach(item => {
      const percentage = totalConditionItems > 0 ? Math.round((item.value / totalConditionItems) * 100) : 0;
      csvRows.push(`"${item.name}",${item.value},${percentage}%`);
    });
    csvRows.push(`"TOTAL",${totalConditionItems},100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === LOW STOCK ALERTS ===
    if (lowStockAlerts.length > 0) {
      csvRows.push("⚠️ LOW STOCK ALERTS - IMMEDIATE ATTENTION REQUIRED");
      csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
      csvRows.push(""); // Separator
      csvRows.push("Priority,Asset Name,SKU,Category,Current Qty,Minimum Qty,Shortage,Status,Action Required");
      
      lowStockAlerts.forEach((item, index) => {
        const shortage = item.minimum - item.current;
        const priority = item.current === 0 ? "CRITICAL" : shortage > 10 ? "HIGH" : "MEDIUM";
        const status = item.current === 0 ? "OUT OF STOCK" : "LOW STOCK";
        const action = item.current === 0 ? "Order Immediately" : `Restock ${shortage} units`;
        
        csvRows.push(
          `"${priority}","${item.name}","${item.sku}","${item.category}",${item.current},${item.minimum},${shortage},"${status}","${action}"`
        );
      });
      csvRows.push(""); // Separator
      csvRows.push(""); // Separator
    }
    
    // === MONTHLY ACQUISITION TREND ===
    csvRows.push("MONTHLY ACQUISITION TREND (Last 6 Months)");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Month,Assets Acquired,Assets Retired,Net Change");
    
    monthlyAcquisition.forEach(month => {
      const netChange = month.acquired - month.retired;
      const changeIndicator = netChange > 0 ? `+${netChange}` : netChange.toString();
      csvRows.push(`"${month.month}",${month.acquired},${month.retired},"${changeIndicator}"`);
    });
    
    const totalAcquired = monthlyAcquisition.reduce((sum, m) => sum + m.acquired, 0);
    const totalRetired = monthlyAcquisition.reduce((sum, m) => sum + m.retired, 0);
    const netTotal = totalAcquired - totalRetired;
    csvRows.push(`"TOTAL",${totalAcquired},${totalRetired},"${netTotal > 0 ? '+' : ''}${netTotal}"`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === FOOTER ===
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(""); // Separator
    csvRows.push("REPORT NOTES:");
    csvRows.push("• This report contains confidential inventory information");
    csvRows.push("• All values are in Philippine Peso (₱)");
    csvRows.push("• Low Stock threshold is based on Minimum Quantity settings");
    csvRows.push(`• Report includes ${inventory.length} unique inventory items with total quantity of ${totalAssets} assets`);
    csvRows.push("• For questions or discrepancies, contact the Inventory Management Team");
    csvRows.push(""); // Separator
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(`Digital Minds BPO Services Inc. © ${new Date().getFullYear()} | Inventory Management System v1.0`);
    
    // Create CSV blob and download
    const csvContent = csvRows.join("\n");
    const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" }); // BOM for proper Excel encoding
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", `DigitalMinds_Inventory_Report_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    toast.success("Professional CSV report downloaded successfully!");
  };

  if (inventoryLoading || assignmentsLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#B0BF00] mx-auto mb-2"></div>
          <p className="text-sm text-gray-500">Loading reports...</p>
        </div>
      </div>
    );
  }

  // Calculate real stats from database
  const totalAssets = inventory.reduce((sum, item) => sum + item.quantity, 0);
  const totalInStock = inventory.filter(i => i.stockStatus === "In Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalLowStock = inventory.filter(i => i.stockStatus === "Low Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalOutOfStock = inventory.filter(i => i.stockStatus === "Out of Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalUnderMaintenance = assignments.filter(a => a.status === "Under Maintenance").length;
  const totalInventoryValue = inventory.reduce((sum, item) => sum + (item.price * item.quantity), 0);

  // Summary stats with real data
  const summaryStats = [
    {
      label: "Total Assets",
      value: totalAssets.toString(),
      sub: "Across all types",
      icon: Package,
      iconBg: "bg-blue-50",
      iconColor: "text-blue-500",
      trend: `${inventory.length} unique items`,
      up: true,
    },
    {
      label: "In Stock",
      value: totalInStock.toString(),
      sub: `${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of total`,
      icon: CheckCircle,
      iconBg: "bg-green-50",
      iconColor: "text-green-500",
      trend: "Well stocked",
      up: true,
    },
    {
      label: "Low / Out of Stock",
      value: (totalLowStock + totalOutOfStock).toString(),
      sub: "Needs attention",
      icon: AlertTriangle,
      iconBg: "bg-amber-50",
      iconColor: "text-amber-500",
      trend: `${totalOutOfStock} out of stock`,
      up: false,
    },
    {
      label: "Under Maintenance",
      value: totalUnderMaintenance.toString(),
      sub: "Being serviced",
      icon: Clock,
      iconBg: "bg-purple-50",
      iconColor: "text-purple-500",
      trend: "Active maintenance",
      up: true,
    },
  ];

  // Stock by category with real data
  const stockByType = (() => {
    const categories = ["System Unit", "Monitor", "Keyboard", "Mouse", "Headset", "Webcam", "Extra"];
    return categories.map(cat => {
      const items = inventory.filter(i => i.category === cat);
      return {
        name: cat,
        inStock: items.filter(i => i.stockStatus === "In Stock").reduce((s, i) => s + i.quantity, 0),
        lowStock: items.filter(i => i.stockStatus === "Low Stock").reduce((s, i) => s + i.quantity, 0),
        outOfStock: items.filter(i => i.stockStatus === "Out of Stock").reduce((s, i) => s + i.quantity, 0),
        total: items.reduce((s, i) => s + i.quantity, 0),
      };
    }).filter(cat => cat.total > 0); // Only show categories with items
  })();

  // Monthly acquisition from purchase dates
  const monthlyAcquisition = (() => {
    const months = ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"];
    const now = new Date();
    const monthlyCounts: Record<string, { acquired: number; retired: number }> = {};
    
    months.forEach(m => monthlyCounts[m] = { acquired: 0, retired: 0 });
    
    inventory.forEach(item => {
      if (item.purchaseDate) {
        const purchaseDate = new Date(item.purchaseDate);
        const monthDiff = (now.getFullYear() - purchaseDate.getFullYear()) * 12 + (now.getMonth() - purchaseDate.getMonth());
        
        if (monthDiff >= 0 && monthDiff < 6) {
          const monthName = months[5 - monthDiff];
          if (monthName) {
            monthlyCounts[monthName].acquired += item.quantity;
          }
        }
      }
    });
    
    return months.map(month => ({
      month,
      acquired: monthlyCounts[month].acquired,
      retired: monthlyCounts[month].retired, // No retirement data in current schema
    }));
  })();

  // Condition data with real data
  const conditionData = (() => {
    const conditions: Record<string, number> = {
      "Excellent": 0,
      "Good": 0,
      "Fair": 0,
      "Poor": 0,
      "Damaged": 0,
    };
    
    inventory.forEach(item => {
      const cond = item.condition || "Good";
      if (conditions[cond] !== undefined) {
        conditions[cond] += item.quantity;
      } else {
        conditions["Good"] += item.quantity; // Default to Good if unknown
      }
    });
    
    const colors: Record<string, string> = {
      "Excellent": "#B0BF00",
      "Good": "#1a1d27",
      "Fair": "#94a3b8",
      "Poor": "#ef4444",
      "Damaged": "#dc2626",
    };
    
    return Object.entries(conditions)
      .filter(([_, value]) => value > 0)
      .map(([name, value]) => ({
        name,
        value,
        color: colors[name],
      }));
  })();

  // Inventory value by category with real data
  const inventoryValueByCategory = (() => {
    const categories = ["System Unit", "Monitor", "Keyboard", "Mouse", "Headset", "Webcam", "Extra"];
    const categoryValues = categories.map(cat => {
      const items = inventory.filter(i => i.category === cat);
      const value = items.reduce((s, i) => s + (i.price * i.quantity), 0);
      return { name: cat, value };
    }).filter(cat => cat.value > 0);
    
    const total = categoryValues.reduce((s, c) => s + c.value, 0);
    
    return categoryValues.map(cat => ({
      ...cat,
      percentage: total > 0 ? Math.round((cat.value / total) * 100) : 0,
    }));
  })();

  // Top assets by value with real data
  const topAssets = inventory
    .map(item => ({
      name: item.assetName,
      sku: item.sku,
      category: item.category,
      qty: item.quantity,
      price: item.price,
      totalValue: item.price * item.quantity,
      stockStatus: item.stockStatus,
      assetStatus: item.assetStatus,
      condition: item.condition || "Good",
    }))
    .sort((a, b) => b.totalValue - a.totalValue)
    .slice(0, 8);

  // Low stock alerts with real data
  const lowStockAlerts = inventory
    .filter(item => item.stockStatus === "Low Stock" || item.stockStatus === "Out of Stock")
    .map(item => ({
      name: item.assetName,
      sku: item.sku,
      current: item.quantity,
      minimum: item.minQuantity,
      category: item.category,
    }))
    .sort((a, b) => a.current - b.current)
    .slice(0, 10);

  const currentDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return (
    <>
      <style>
        {`
          @media print {
            body * {
              visibility: hidden;
            }
            #print-content, #print-content * {
              visibility: visible;
            }
            #print-content {
              position: absolute;
              left: 0;
              top: 0;
              width: 100%;
            }
            @page {
              margin: 0.5in;
            }
          }
        `}
      </style>

      <div className="space-y-5">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-gray-800">Reports & Analytics</h2>
            <p className="text-xs text-gray-500 mt-0.5">BPO Equipment Inventory — Digital Minds</p>
          </div>
          <div className="flex items-center gap-2">
            <select
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="text-xs border border-gray-200 rounded-lg px-2.5 py-1.5 bg-white text-gray-600 outline-none focus:border-[#B0BF00]"
            >
              <option value="3months">Last 3 Months</option>
              <option value="6months">Last 6 Months</option>
              <option value="year">This Year</option>
            </select>
            <button
              onClick={() => setShowFormatDialog(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-[#B0BF00] hover:bg-[#9aaa00] text-white rounded-lg text-xs font-medium transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              Generate Report
            </button>
            <button
              onClick={() => handleExport("Full")}
              className="flex items-center gap-1.5 px-3 py-1.5 border border-gray-200 rounded-lg text-xs font-medium text-gray-600 hover:bg-gray-50 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Export
            </button>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {summaryStats.map((stat, i) => {
            const Icon = stat.icon;
            return (
              <div key={i} className={CARD}>
                <div className="flex items-start gap-3">
                  <div className={`${stat.iconBg} ${stat.iconColor} p-2.5 rounded-lg flex-shrink-0`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs text-gray-500">{stat.label}</p>
                    <p className="text-2xl font-semibold text-gray-800 mt-0.5">{stat.value}</p>
                    <p className="text-[10px] text-gray-400 mt-0.5">{stat.sub}</p>
                  </div>
                </div>
                <div className={`mt-3 flex items-center gap-1 text-[10px] font-medium ${stat.up ? "text-green-600" : "text-orange-500"}`}>
                  {stat.up ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
                  {stat.trend}
                </div>
              </div>
            );
          })}
        </div>

        {/* Charts Row 1 */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* Stock by Category */}
          <div className={CARD}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-gray-800">Stock by Asset Type</h3>
              <button onClick={() => handleExport("Stock by Type")} className="p-1 text-gray-400 hover:text-gray-600 rounded">
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={stockByType} barSize={14} barCategoryGap="30%">
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
                <XAxis dataKey="name" tick={{ fontSize: 9, fill: "#94a3b8" }} axisLine={false} tickLine={false} angle={-15} textAnchor="end" height={50} />
                <YAxis tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
                <Tooltip
                  contentStyle={{ backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px", fontSize: "11px" }}
                />
                <Legend wrapperStyle={{ fontSize: "10px", paddingTop: "8px" }} />
                <Bar dataKey="inStock" fill="#B0BF00" name="In Stock" radius={[3, 3, 0, 0]} />
                <Bar dataKey="lowStock" fill="#f97316" name="Low Stock" radius={[3, 3, 0, 0]} />
                <Bar dataKey="outOfStock" fill="#ef4444" name="Out of Stock" radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Asset Condition Distribution */}
          <div className={CARD}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-gray-800">Asset Condition</h3>
              <button onClick={() => handleExport("Condition")} className="p-1 text-gray-400 hover:text-gray-600 rounded">
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <div className="flex flex-col items-center">
              <ResponsiveContainer width="100%" height={160}>
                <PieChart>
                  <Pie data={conditionData} cx="50%" cy="50%" innerRadius={45} outerRadius={70} paddingAngle={2} dataKey="value" strokeWidth={0}>
                    {conditionData.map((entry, index) => (
                      <Cell key={`condition-cell-${entry.name}-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip contentStyle={{ backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px", fontSize: "11px" }} />
                </PieChart>
              </ResponsiveContainer>
              <div className="grid grid-cols-3 gap-x-4 gap-y-1.5 w-full mt-2">
                {conditionData.map((d, i) => (
                  <div key={i} className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ backgroundColor: d.color }} />
                    <span className="text-[10px] text-gray-500">{d.name} ({d.value})</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Inventory Value by Category */}
        <div className={CARD}>
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-gray-800">Inventory Value Distribution by Category</h3>
            <button onClick={() => handleExport("Value Distribution")} className="p-1 text-gray-400 hover:text-gray-600 rounded">
              <Download className="w-3.5 h-3.5" />
            </button>
          </div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={inventoryValueByCategory} layout="vertical" barSize={20}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <YAxis dataKey="name" type="category" tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} width={100} />
              <Tooltip
                contentStyle={{ backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px", fontSize: "11px" }}
                formatter={(value: number) => `₱${value.toLocaleString()}`}
              />
              <Bar dataKey="value" fill="#B0BF00" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Charts Row 2 */}
        <div className={CARD}>
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-gray-800">Monthly Acquisitions vs Retirements</h3>
            <button onClick={() => handleExport("Acquisitions")} className="p-1 text-gray-400 hover:text-gray-600 rounded">
              <Download className="w-3.5 h-3.5" />
            </button>
          </div>
          <ResponsiveContainer width="100%" height={200}>
            <AreaChart data={monthlyAcquisition}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
              <XAxis dataKey="month" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: "8px", fontSize: "11px" }} />
              <Legend wrapperStyle={{ fontSize: "11px" }} />
              <Area type="monotone" dataKey="acquired" stroke="#B0BF00" fill="#B0BF00" fillOpacity={0.15} strokeWidth={2} name="Acquired" />
              <Area type="monotone" dataKey="retired" stroke="#ef4444" fill="#ef4444" fillOpacity={0.1} strokeWidth={2} name="Retired" />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        {/* Tables Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* Top Assets */}
          <div className={CARD}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-gray-800">Top Assets by Value</h3>
              <button onClick={() => handleExport("Top Assets")} className="p-1 text-gray-400 hover:text-gray-600 rounded">
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-100">
                  <th className="text-left pb-2 text-[10px] font-semibold text-gray-400 uppercase">Asset</th>
                  <th className="text-right pb-2 text-[10px] font-semibold text-gray-400 uppercase">Qty</th>
                  <th className="text-right pb-2 text-[10px] font-semibold text-gray-400 uppercase">Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {topAssets.slice(0, 5).map((item, i) => (
                  <tr key={i}>
                    <td className="py-2.5">
                      <p className="text-xs font-medium text-gray-700">{item.name}</p>
                      <p className="text-[10px] text-gray-400 font-mono">{item.sku}</p>
                    </td>
                    <td className="py-2.5 text-right text-xs text-gray-600">{item.qty}</td>
                    <td className="py-2.5 text-right text-xs font-semibold text-gray-800">₱{item.totalValue.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Low Stock Alerts */}
          <div className={CARD}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-gray-800">Low Stock Alerts</h3>
              <span className="text-[10px] font-semibold bg-red-50 text-red-500 px-2 py-0.5 rounded-full border border-red-100">
                {lowStockAlerts.length} assets
              </span>
            </div>
            <div className="space-y-3">
              {lowStockAlerts.map((item, i) => {
                const pct = item.minimum > 0 ? Math.min((item.current / item.minimum) * 100, 100) : 0;
                const isOut = item.current === 0;
                return (
                  <div key={i} className="space-y-1">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-xs font-medium text-gray-700">{item.name}</p>
                        <p className="text-[10px] text-gray-400">{item.category} · {item.sku}</p>
                      </div>
                      <div className="text-right">
                        <span className={`text-xs font-semibold ${isOut ? "text-red-500" : "text-orange-500"}`}>
                          {item.current} / {item.minimum}
                        </span>
                        <p className="text-[10px] text-gray-400">current / min</p>
                      </div>
                    </div>
                    <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${isOut ? "bg-red-400" : "bg-orange-400"}`}
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
            <button className="mt-4 w-full text-xs text-[#B0BF00] hover:underline font-medium">
              View all low stock assets →
            </button>
          </div>
        </div>
      </div>

      {/* Printable Report Template */}
      {showPrintPreview && (
        <div
          id="print-content"
          ref={printRef}
          className="hidden print:block fixed inset-0 bg-white z-50 overflow-auto"
          style={{ display: showPrintPreview ? "block" : "none" }}
        >
          <div className="max-w-[8.5in] mx-auto p-8 bg-white">
            {/* Report Header */}
            <div className="border-b-2 border-[#B0BF00] pb-6 mb-6">
              <div className="flex items-start justify-between">
                <div>
                  <img
                    src="https://cdn.digitalmindsbpo.com/wp-content/uploads/2021/11/cropped-Digital_Minds_Logo_Original.png"
                    alt="Digital Minds BPO"
                    className="h-12 mb-3"
                  />
                  <p className="text-xs text-gray-600">Digital Minds BPO Services Incorporated</p>
                </div>
                <div className="text-right">
                  <h1 className="text-2xl font-bold text-gray-900 mb-1">Asset Summary Report</h1>
                  <p className="text-xs text-gray-500">Generated on: {currentDate}</p>
                  <p className="text-xs text-gray-500">Generated by: Jeremy Sendon (Admin)</p>
                </div>
              </div>
            </div>

            {/* Summary Statistics */}
            <div className="grid grid-cols-3 gap-4 mb-8">
              <div className="bg-gradient-to-br from-blue-50 to-blue-100 p-4 rounded-lg border border-blue-200">
                <p className="text-xs text-blue-600 font-medium mb-1">Total Assets</p>
                <p className="text-3xl font-bold text-blue-900">{totalAssets}</p>
                <p className="text-xs text-blue-600 mt-1">Across all categories</p>
              </div>
              <div className="bg-gradient-to-br from-green-50 to-green-100 p-4 rounded-lg border border-green-200">
                <p className="text-xs text-green-600 font-medium mb-1">Total Assets in Stock</p>
                <p className="text-3xl font-bold text-green-900">{totalInStock}</p>
                <p className="text-xs text-green-600 mt-1">{Math.round((totalInStock / totalAssets) * 100)}% of total inventory</p>
              </div>
              <div className="bg-gradient-to-br from-[#B0BF00]/10 to-[#B0BF00]/20 p-4 rounded-lg border border-[#B0BF00]/30">
                <p className="text-xs text-[#8BA000] font-medium mb-1">Total Inventory Value</p>
                <p className="text-3xl font-bold text-[#6d7a00]">₱{totalInventoryValue.toLocaleString()}</p>
                <p className="text-xs text-[#8BA000] mt-1">Current market value</p>
              </div>
            </div>

            {/* Asset Distribution by Category */}
            <div className="mb-8">
              <h2 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
                Asset Distribution by Category
              </h2>
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50 border-y border-gray-200">
                    <th className="text-left py-2 px-3 text-xs font-semibold text-gray-700">Category</th>
                    <th className="text-center py-2 px-3 text-xs font-semibold text-gray-700">In Stock</th>
                    <th className="text-center py-2 px-3 text-xs font-semibold text-gray-700">Low Stock</th>
                    <th className="text-center py-2 px-3 text-xs font-semibold text-gray-700">Out of Stock</th>
                    <th className="text-right py-2 px-3 text-xs font-semibold text-gray-700">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {stockByType.map((item, i) => (
                    <tr key={i} className="border-b border-gray-100">
                      <td className="py-2 px-3 text-sm text-gray-800">{item.name}</td>
                      <td className="py-2 px-3 text-sm text-center text-green-600 font-medium">{item.inStock}</td>
                      <td className="py-2 px-3 text-sm text-center text-orange-500 font-medium">{item.lowStock}</td>
                      <td className="py-2 px-3 text-sm text-center text-red-500 font-medium">{item.outOfStock}</td>
                      <td className="py-2 px-3 text-sm text-right font-semibold text-gray-900">{item.total}</td>
                    </tr>
                  ))}
                  <tr className="bg-gray-50 font-semibold border-t-2 border-gray-300">
                    <td className="py-2 px-3 text-sm text-gray-900">Total</td>
                    <td className="py-2 px-3 text-sm text-center text-green-700">{stockByType.reduce((sum, item) => sum + item.inStock, 0)}</td>
                    <td className="py-2 px-3 text-sm text-center text-orange-600">{stockByType.reduce((sum, item) => sum + item.lowStock, 0)}</td>
                    <td className="py-2 px-3 text-sm text-center text-red-600">{stockByType.reduce((sum, item) => sum + item.outOfStock, 0)}</td>
                    <td className="py-2 px-3 text-sm text-right text-gray-900">{totalAssets}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Detailed Asset Inventory */}
            <div className="mb-8">
              <h2 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
                Detailed Asset Inventory
              </h2>
              <table className="w-full border-collapse text-xs">
                <thead>
                  <tr className="bg-gray-50 border-y border-gray-200">
                    <th className="text-left py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Name</th>
                    <th className="text-left py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">SKU</th>
                    <th className="text-left py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Category</th>
                    <th className="text-center py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Qty</th>
                    <th className="text-right py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Price</th>
                    <th className="text-right py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Total Value</th>
                    <th className="text-center py-2 px-2 text-[10px] font-semibold text-gray-700 uppercase">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {topAssets.map((item, i) => (
                    <tr key={i} className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="py-2 px-2 text-xs text-gray-800">{item.name}</td>
                      <td className="py-2 px-2 text-xs text-gray-600 font-mono">{item.sku}</td>
                      <td className="py-2 px-2 text-xs text-gray-700">{item.category}</td>
                      <td className="py-2 px-2 text-xs text-center text-gray-800">{item.qty}</td>
                      <td className="py-2 px-2 text-xs text-right text-gray-700">₱{item.price.toLocaleString()}</td>
                      <td className="py-2 px-2 text-xs text-right font-semibold text-gray-900">₱{item.totalValue.toLocaleString()}</td>
                      <td className="py-2 px-2 text-center">
                        <span
                          className={`inline-block px-2 py-0.5 rounded text-[9px] font-semibold uppercase ${
                            item.stockStatus === "In Stock"
                              ? "bg-green-100 text-green-700"
                              : item.stockStatus === "Low Stock"
                              ? "bg-orange-100 text-orange-700"
                              : "bg-red-100 text-red-700"
                          }`}
                        >
                          {item.stockStatus}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Low Stock Alerts */}
            {lowStockAlerts.length > 0 && (
              <div className="mb-8">
                <h2 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-orange-500" />
                  Low Stock Alerts
                </h2>
                <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-orange-200">
                        <th className="text-left py-2 text-xs font-semibold text-orange-900">Asset</th>
                        <th className="text-left py-2 text-xs font-semibold text-orange-900">Category</th>
                        <th className="text-center py-2 text-xs font-semibold text-orange-900">Current</th>
                        <th className="text-center py-2 text-xs font-semibold text-orange-900">Minimum</th>
                        <th className="text-center py-2 text-xs font-semibold text-orange-900">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {lowStockAlerts.map((item, i) => (
                        <tr key={i} className="border-b border-orange-100 last:border-0">
                          <td className="py-2 text-xs text-gray-800">
                            <div>{item.name}</div>
                            <div className="text-[10px] text-gray-500 font-mono">{item.sku}</div>
                          </td>
                          <td className="py-2 text-xs text-gray-700">{item.category}</td>
                          <td className="py-2 text-xs text-center font-semibold text-orange-700">{item.current}</td>
                          <td className="py-2 text-xs text-center text-gray-700">{item.minimum}</td>
                          <td className="py-2 text-center">
                            <span className={`inline-block px-2 py-0.5 rounded text-[9px] font-semibold uppercase ${
                              item.current === 0 ? "bg-red-100 text-red-700" : "bg-orange-100 text-orange-700"
                            }`}>
                              {item.current === 0 ? "Out of Stock" : "Low Stock"}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Condition Summary */}
            <div className="mb-8">
              <h2 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
                Asset Condition Summary
              </h2>
              <div className="grid grid-cols-5 gap-3">
                {conditionData.map((item, i) => (
                  <div key={i} className="text-center p-3 rounded-lg border border-gray-200 bg-gray-50">
                    <div className="w-3 h-3 rounded-full mx-auto mb-2" style={{ backgroundColor: item.color }} />
                    <p className="text-xs font-medium text-gray-700">{item.name}</p>
                    <p className="text-xl font-bold text-gray-900 mt-1">{item.value}</p>
                    <p className="text-[10px] text-gray-500">{Math.round((item.value / conditionData.reduce((sum, d) => sum + d.value, 0)) * 100)}%</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Footer */}
            <div className="border-t-2 border-gray-200 pt-4 mt-8">
              <div className="flex items-center justify-between text-xs text-gray-500">
                <p>Digital Minds BPO Services Inc.</p>
                <div className="flex items-center gap-4">
                  <p>Page 1</p>
                  <div className="w-6 h-6 bg-[#B0BF00] rounded" />
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Format Dialog */}
      <Dialog open={showFormatDialog} onOpenChange={setShowFormatDialog}>
        <DialogContent className="sm:max-w-md rounded-xl">
          <DialogHeader>
            <DialogTitle>Choose Report Format</DialogTitle>
            <DialogDescription>Select the format in which you want to generate the report.</DialogDescription>
          </DialogHeader>
          <div className="flex items-center justify-center gap-4 py-4">
            <button
              onClick={() => handleGenerateReport("pdf")}
              className="flex-1 flex flex-col items-center gap-2 px-6 py-4 bg-[#B0BF00] hover:bg-[#9aaa00] text-white rounded-lg font-medium transition-colors"
            >
              <FileText className="w-8 h-8" />
              <span className="text-sm">PDF Report</span>
              <span className="text-xs opacity-80">Print-ready format</span>
            </button>
            <button
              onClick={() => handleGenerateReport("csv")}
              className="flex-1 flex flex-col items-center gap-2 px-6 py-4 border-2 border-[#B0BF00] text-[#B0BF00] hover:bg-[#B0BF00]/5 rounded-lg font-medium transition-colors"
            >
              <File className="w-8 h-8" />
              <span className="text-sm">CSV Export</span>
              <span className="text-xs opacity-80">Spreadsheet format</span>
            </button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}